# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'

#- task: VSBuild@1
#  inputs:
#    solution: '$(solution)'
#    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  displayName: 'Veracode SCA scan'
  #env: {SRCCLR_API_TOKEN: $(apiToken), DEBUG: "1"}
  #env: {SRCCLR_API_TOKEN: $(SRCCLR_API_TOKEN), SRCCLR_USE_DOTNET_EXEC: 'DOTNET'}
  env:{SRCCLR_API_TOKEN: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzA1NTMxLCJleHAiOjE2NTY0NDM5MzgsImF1dGhvcml0aWVzIjoiQUdFTlQiLCJqdGkiOiI0NDUwMmI1NS02MTE1LTQ2OGMtOWIzZS1hOTZlY2EzMzA2YjEiLCJjbGllbnRfaWQiOiIiLCJzY29wZSI6W119.bBpxk4SXj14OO0fJST3GTI08YHYiIUpWS0SA2-rWQXYN2Itzkyzm0y-4d6SXcpPz4P7hxV7Fdy1UjE2boXtABZaw4p2qZRUzvBKspxkg11Bw9NNt_OmUT-2OT3_qHhg4MkaMyWflUlSt_wL2LNYNWiQKiU8geApYRwgf8SaUtUw"}
  inputs:
   targetType: 'inline'
   script: |
    Set-ExecutionPolicy AllSigned -Scope Process -Force
    $ProgressPreference = "SilentlyContinue"
    iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
    srcclr scan $(Build.SourcesDirectory)
