# ASP.NET

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  system.debug: true

steps:
- task: NuGetToolInstaller@1

#- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    veracodeAppProfile: '$(system.teamProject)'
    version: '$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    maximumWaitTime: '360'
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4


#task: PowerShell@2
  #displayName: 'Veracode SCA scan'
  #inputs:
   #targetType: 'inline'
   #script: |
    #Set-ExecutionPolicy AllSigned -Scope Process -Force
    #$ProgressPreference = "SilentlyContinue"
    #iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
    #srcclr scan $(Build.SourcesDirectory)
